# Fundamentos de TensorFlow

En Machine Learning, los datos con los que trabajamos se representan en forma de tensores. Los tensores son una generalización de matrices y vectores a una cantidad arbitraria de dimensiones.

## Contenido:

* Introducción a tensors
* Obtener información de tensores
* Manipulación de tensores
* Tensores y Numpy
* Uso de @tf.function (una forma de acelerar tu código)
* Uso de GPUs con TensorFlow
* Ejercicios para practicar

## Introducción a tensores

In [1]:
# import Tensorflow

import tensorflow as tf
print(tf.__version__)

2.6.0


In [2]:
# creando un tensor con tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# verificando el número de dimensiones de un tensor (ndim)
scalar.ndim

0

In [5]:
# creando un vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [6]:
vector.ndim

1

In [7]:
# creando una matriz ( tiene mas de 1 dimensión)
matrix = tf.constant([[10, 7],
                        [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [8]:
matrix.ndim

2

In [12]:
# creando otro matriz pero modificando el tipo de dato

another_matrix = tf.constant([[10., 7.],
                                [3., 2.],
                                [8., 9.]], dtype=tf.float16) # especificando el tipo de dato
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [13]:
# numero de dimensiones de another_matrix
another_matrix.ndim

2

In [14]:
# creando un tensor
tensor = tf.constant([[[1, 2, 3,],
                        [4, 5, 6]],
                        [[7, 8, 9],
                        [10, 11, 12]],
                        [[13, 14, 15],
                        [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [15]:
# verificando el número de dimensiones de un tensor
tensor.ndim

3

### Resumen

* Scalar: Un tensor de 0 dimensiones (un número).
* Vector: Un tensor de 1 dimensión (un array de números). Numero con dirección.
* Matrix: Un tensor de 2 dimensiones (un array de arrays de números).
* Tensor: Un tensor de n dimensiones (un array de n-1 dimensiones de números).  