# Fundamentos de TensorFlow

En Machine Learning, los datos con los que trabajamos se representan en forma de tensores. Los tensores son una generalización de matrices y vectores a una cantidad arbitraria de dimensiones.

## Contenido:

* Introducción a tensors
* Obtener información de tensores
* Manipulación de tensores
* Tensores y Numpy
* Uso de @tf.function (una forma de acelerar tu código)
* Uso de GPUs con TensorFlow
* Ejercicios para practicar

<a href="https://is.gd/NH41Td"><img src="https://is.gd/NH41Td" alt="Tensor" border="0" width="400"></a>

[Referencia: TensorFlow Fundamentals](https://is.gd/N40snM)

## Introducción a tensores

In [1]:
# import Tensorflow

import tensorflow as tf
print(tf.__version__)

2.6.0


In [2]:
# creando un tensor con tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# verificando el número de dimensiones de un tensor (ndim)
scalar.ndim

0

In [4]:
# creando un vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [5]:
vector.ndim

1

In [6]:
# creando una matriz ( tiene mas de 1 dimensión)
matrix = tf.constant([[10, 7],
                        [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [7]:
matrix.ndim

2

In [8]:
# creando otro matriz pero modificando el tipo de dato

another_matrix = tf.constant([[10., 7.],
                                [3., 2.],
                                [8., 9.]], dtype=tf.float16) # especificando el tipo de dato
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
# numero de dimensiones de another_matrix
another_matrix.ndim

2

In [10]:
# creando un tensor
tensor = tf.constant([[[1, 2, 3,],
                        [4, 5, 6]],
                        [[7, 8, 9],
                        [10, 11, 12]],
                        [[13, 14, 15],
                        [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [11]:
# verificando el número de dimensiones de un tensor
tensor.ndim

3

### Resumen

* Scalar: Un tensor de 0 dimensiones (un número).
* Vector: Un tensor de 1 dimensión (un array de números). Numero con dirección.
* Matrix: Un tensor de 2 dimensiones (un array de arrays de números).
* Tensor: Un tensor de n dimensiones (un array de n-1 dimensiones de números).  

### Creando tensores con `tf.Variable`

In [12]:
# creando un tensor con tf.Variable
changeable_tensor = tf.Variable([10, 7]) # se puede cambiar	
unchangeable_tensor = tf.constant([10, 7]) # no se puede cambiar

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [13]:
# intentando cambiar un elemento del tensor changeable_tensor
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

### Creando tensores random con `tf.random.Generator`

Los tensores random son útiles **para inicializar los pesos de una red neuronal** (o cualquier otro tipo de tensor) con valores aleatorios.

In [14]:
random_1 = tf.random.Generator.from_seed(42) # estableciendo la semilla para reproducibilidad
random_1 = random_1.normal(shape=(3, 2)) # creando una matriz normal con media 0 y desviación estándar 1
random_2 = tf.random.Generator.from_seed(42) # estableciendo la semilla para reproducibilidad
random_2 = random_2.normal(shape=(3, 2)) # creando una matriz normal con media 0 y desviación estándar 1

# comprobando si los valores de random_1 y random_2 son iguales
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle(Barajar) el orden de los elementos en un tensor (de forma aleatoria)

Se utiliza la función `tf.random.shuffle()`, cuando se queire barajar el orden de los elementos en un tensor para no afectar el aprendizaje de la red neuronal.


In [15]:
# shuffling el orden de los elementos de un tensor
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

Si queremos que el orden de los elementos en un tensor sea siempre el mismo, debemos establecer la semilla global (seed) con `tf.random.set_seed()` y adicionalmente utilizar la semilla local en la función `tf.random.shuffle()`.
https://www.tensorflow.org/api_docs/python/tf/random/set_seed

> **Nota:** La semilla global solo afecta a las operaciones random que no reciban una semilla local. Si se establece la semilla global y se utiliza una semilla local en una operación random, la semilla local tendrá prioridad.

> **Regla #4:** "If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."

In [16]:
# shuffling el orden de los elementos de un tensor
tf.random.set_seed(42) # semilla global, se aplica a todas las operaciones aleatorias
tf.random.shuffle(not_shuffled, seed=42) # semilla local, solo se aplica a esta operación

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

### Otra forma de crear tensores

Crear tensores con `tf.ones()` y `tf.zeros()`.

In [17]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [18]:
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Convirtiendo un tensor de NumPy a un tensor de TensorFlow

La diferencia principal entre un tensor de NumPy y un tensor de TensorFlow es que los tensores de TensorFlow pueden ejecutarse en una GPU (o TPU) para acelerar la computación.


> X = tf.constant(some_matrix) # Se utiliza la mayuscula para indicar que es una matriz
>
> y = tf.constant(vector) # Se utiliza la minuscula para indicar que es un vector


In [19]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # creando un tensor de NumPy
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [20]:
# shape = (2, 3, 4) significa que hay 2 matrices, cada una con 3 filas y 4 columnas, 
# la multiplicación de estos números debe ser igual a 24, que es el número de elementos en el tensor original.

A = tf.constant(numpy_A,shape=(2, 3, 4)) # convirtiendo un tensor de NumPy a un tensor de TensorFlow
B = tf.constant(numpy_A) # convirtiendo un tensor de NumPy a un tensor de TensorFlow
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>)

### Obtener información de tensores

Cuando estamos trabajando con tensores, es importante conocer las siguientes propiedades:

1. **Forma (shape)**: El número de dimensiones del tensor y el tamaño de cada dimensión. `tensor.shape`.
2. **Rango (rank)** o número de dimensiones (ndim): El número de dimensiones del tensor. `tensor.ndim`.
3. **Axis** o dimension (axis or axes) o eje: Una dimensión de un tensor. `tensor[0], tensor[:, 1]`.
4. **Tamaño** (size) o número de elementos: El número de elementos a lo largo de un tensor. `tf.size(tensor)`.


In [21]:
# creando un tensor de rank 4 (4 dimensiones)
# shape = (2, 3, 4, 5) significa que hay 2 matrices, cada una con 3 matrices, cada una con 4 vectores, cada uno con 5 escalares
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5]) 
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [22]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [23]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor).numpy()

(TensorShape([2, 3, 4, 5]), 4, 120)

In [24]:
# obteniendo varios atributos de el tensor

print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5): ", tf.size(rank_4_tensor).numpy())


Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along the last axis of tensor: 5
Total number of elements (2*3*4*5):  120


### Indexando y manipulando tensores

- Los tensores pueden indexarse de la misma forma que las listas de Python. 
- Los tensores también pueden manipularse (slice) de la misma forma que las listas de Python.


In [25]:
# obteniendo el primer y último elemento de un tensor
print(rank_4_tensor[0, 0, 0, 0]) # primer elemento
print(rank_4_tensor[-1, -1, -1, -1]) # el último elemento

tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)


In [26]:
# obtener los primeros 2 elementos a lo largo de todas las dimensiones
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [27]:
# obtener el primer elemento de cada dimensión excepto la última.

rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
# obtener el primer elemento de cada dimensión excepto la penúltima.
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [29]:
# agregar una dimensión extra al final de un tensor. 
# crear un tensor de rank 2 (2 dimensiones)

rank_2_tensor = tf.constant([[10, 7],
                            [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [30]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [31]:
# obtener el ultimo elemento de cada fila de un tensor de rank 2
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

In [32]:
# agregar una dimensión extra al final de un tensor.
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [33]:
# podemos hacer lo mismo con tf.expand_dims()
tf.expand_dims(rank_2_tensor, axis=-1) # -1 significa la última dimensión

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [34]:
# podemos hacer lo mismo con tf.expand_dims()
tf.expand_dims(rank_2_tensor, axis=0) # 0 significa la primera dimensión

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]])>

### Manipulando tensores (tensor operations)

Hay muchas operaciones con tensores (además de las básicas de indexación y manipulación) que se pueden realizar.

- **Adición**: `tf.add()`, `+`.
- **Resta**: `tf.subtract()`, `-`.
- **Multiplicación**: `tf.multiply()`, `*`.
- **División**: `tf.divide()`, `/`.
- **Elevar al cuadrado**: `tf.square()`, `**2`.
- **Elevar a la potencia**: `tf.pow()`, `**`.
- **Raíz cuadrada**: `tf.sqrt()`.
- **Producto matricial**: `tf.matmul()`, `@`.
- **Producto de Hadamard**: `tf.tensordot()`, `*` (element-wise product).
- **Cambiar el tipo de un tensor**: `tf.cast()`.

In [35]:
# es posible sumar valores a un tensor utiliznado el operador de adición (+). 
tensor = tf.constant([[10, 7],[3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [36]:
# el tensor original no cambia
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [37]:
# multiplicar un tensor por un escalar
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [38]:
# restar un tensor por un escalar
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [39]:
# es posible utilizar la función tf.multiply()
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [40]:
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

### **Multiplicación de matrices** : 

En machine learning la multiplicación de matrices es una operación muy común. En TensorFlow, la multiplicación de matrices se realiza con `tf.matmul()`.

![Multiplicación de matrices](https://www.mathsisfun.com/algebra/images/matrix-multiply-a.svg)

> The "Dot Product" is where we multiply matching members, then sum up:

(1, 2, 3) • (7, 9, 11) = 1×7 + 2×9 + 3×11
    = 58


Want to see another example? Here it is for the 1st row and 2nd column:

(1, 2, 3) • (8, 10, 12) = 1×8 + 2×10 + 3×12
    = 64

![Multiplicación de matrices](https://www.mathsisfun.com/algebra/images/matrix-multiply-b.svg)


We can do the same thing for the 2nd row and 1st column:

(4, 5, 6) • (7, 9, 11) = 4×7 + 5×9 + 6×11
    = 139

And for the 2nd row and 2nd column:

(4, 5, 6) • (8, 10, 12) = 4×8 + 5×10 + 6×12
    = 154

And we get:

![Multiplicación de matrices](https://www.mathsisfun.com/algebra/images/matrix-multiply-c.svg)


> In General:
>
> To multiply an m×n matrix by an n×p matrix, the ns must be the same,
and the result is an m×p matrix.

![Multiplicación de matrices](https://www.mathsisfun.com/algebra/images/matrix-multiply-rows-cols.svg)


> **Multiplicacion de matrices elemento a elemento** (element wise product): `tf.tensordot()`, `*`.

<a href="https://is.gd/a7dzC0"><img src="https://is.gd/a7dzC0" alt="Multiplicacion" border="0" width="600"></a>


[Referencia: Matrix multiplication](https://is.gd/vTqOrA)

In [41]:
# Multiplicación de matrices en TensorFlow
print(tensor)
tf.matmul(tensor, tensor) # multiplicación de matrices aplicando producto punto

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [42]:
X = tf.constant([[1, 2],
                [3, 4],
                [5, 6]])
Y = tf.constant([[7, 8],
                [9, 10],
                [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [43]:
tf.matmul(X, tf.reshape(Y, shape=(2, 3))) # multiplicación de matrices aplicando producto punto

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [44]:
X @ tf.reshape(Y, shape=(2, 3)) # multiplicación de matrices aplicando producto punto (forma abreviada @) 

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [45]:
tf.matmul(tf.reshape(X, shape=(2, 3)), Y) # multiplicación de matrices aplicando producto punto

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]])>

In [46]:
# la función tf.transpose() cambia el orden de las dimensiones de un tensor
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]])>

In [47]:
# multiplicación de matrices aplicando producto punto y transponiendo el tensor X
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

> **Producto punto** (dot product)

Se puede realizar la operación de producto punto con: 

- `tf.tensordot()`
- `tf.matmul()`.



In [48]:
# Realizar la multiplicación de matrices aplicando producto punto y transponiendo el tensor Y
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [49]:
tf.tensordot(X, tf.transpose(Y), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

Generalmente cuando se realiza la multiplicación de matrices o tensores, se utiliza la operación de transposición de matrices. La transposición de una matriz es una operación que consiste en intercambiar las filas por las columnas. De esta manera se cumplen las reglas de la multiplicación de matrices.

### Cambiando el tipo de dato de un Tensor

In [50]:
# Crear un tensor con el tipo de dato por defecto

B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [51]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [52]:
# convertir un tensor de tipo float32 a float16 (reduciendo la precisión)
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [53]:
# convertir un tensor de tipo int32 a float32
E = tf.cast(C, dtype=tf.float16)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>,
 tf.float16)

### Aggregating tensors

Aggregating tensors = condensar tensores de una forma que reduzca el número de elementos.

In [54]:
# Obtener el valor absoluto
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [55]:
# obtener el valor absoluto
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

Vamos a ver algunas de las principales operaciones de agregación:
- **Obtener el mínimo**: `tf.reduce_min()`.
- **Obtener el máximo**: `tf.reduce_max()`.
- **Obtener la media**: `tf.reduce_mean()`.
- **Obtener la suma**: `tf.reduce_sum()`.
- **Obtener la varianza**: `tf.math.reduce_variance()`.
- **Obtener la desviación estándar**: `tf.math.reduce_std()`.
- **Obtener la suma acumulada**: `tf.math.cumsum()`.
- **Obtener la media acumulada**: `tf.math.cumprod()`.
- **Obtener la moda**: `tf.math.mode()`.
- **Obtener la mediana**: `tf.math.median()`.
- **Obtener el máximo absoluto**: `tf.math.reduce_max()`.
- **Obtener el mínimo absoluto**: `tf.math.reduce_min()`.


In [56]:
# crear un tensor con valores aleatorios entre 0 y 100 de tamaño 50. 

E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([56, 26, 63, 96, 36, 22, 24, 39, 20, 89, 25, 81, 20, 27, 55, 94, 36,
       38, 26, 56, 51, 65, 39, 71, 23,  0, 28, 52, 78, 54, 92, 68, 76, 20,
       20, 82, 33, 22, 65, 95, 33, 56, 62, 29,  0, 32, 10, 95, 89, 49])>

In [57]:
tf.size(E).numpy(), E.shape, E.ndim

(50, TensorShape([50]), 1)

In [58]:
# Encontrar el minimo, máximo, media y la suma de un tensor
tf.reduce_min(E), tf.reduce_max(E), tf.reduce_mean(E), tf.reduce_sum(E)

(<tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=96>,
 <tf.Tensor: shape=(), dtype=int32, numpy=48>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2418>)

In [59]:
# Encontrar la varianza y la desviación estándar de un tensor 
# El tensor debe ser de tipo float16, float32 o float64.
tf.math.reduce_variance(tf.cast(E, dtype=tf.float16)), tf.math.reduce_std(tf.cast(E, dtype=tf.float16))

(<tf.Tensor: shape=(), dtype=float16, numpy=719.5>,
 <tf.Tensor: shape=(), dtype=float16, numpy=26.83>)

### Encontrando la posición (index) del valor máximo y mínimo

In [60]:
# Crear un tensor con 50 valores aleatorios

tf.random.set_seed(42) # establecer la semilla para obtener los mismos valores aleatorios
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [61]:
# Encontrar la posición del valor mínimo y máximo de un tensor
tf.argmax(F), tf.argmin(F)

(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=int64, numpy=16>)

In [62]:
# Encontrar los valores maximos y minimos de un tensor
tf.reduce_max(F), tf.reduce_min(F)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

In [63]:
# Verificar si los valores del index max y min son los mismos que los valores max y min del tensor
F[tf.argmax(F)] == tf.reduce_max(F), F[tf.argmin(F)] == tf.reduce_min(F)

(<tf.Tensor: shape=(), dtype=bool, numpy=True>,
 <tf.Tensor: shape=(), dtype=bool, numpy=True>)

### Squeezing a tensor (removing all single dimensions)

Squeezing a tensor = eliminar todas las dimensiones de tamaño 1.

In [64]:
# crear un tensor con 50 valores aleatorios

G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [65]:
G.shape, G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [66]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape, G_squeezed.ndim

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
        0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
        0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
        0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
        0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
        0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
        0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
        0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
        0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
        0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
       dtype=float32)>,
 TensorShape([50]),
 1)

### One-hot encoding

One-hot encoding = codificación de un tensor en el que solo hay un 1 y el resto son 0.

In [67]:
# crear una lista con indices

some_list = [0, 1, 2, 3] # crear una lista

# one hot encode some_list
depth = len(some_list)
tf.one_hot(some_list, depth=depth)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [68]:
# Especificar valores personalizados para one hot encoding
tf.one_hot(some_list, depth=depth, on_value="I am one!", off_value="I am zero!")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I am one!', b'I am zero!', b'I am zero!', b'I am zero!'],
       [b'I am zero!', b'I am one!', b'I am zero!', b'I am zero!'],
       [b'I am zero!', b'I am zero!', b'I am one!', b'I am zero!'],
       [b'I am zero!', b'I am zero!', b'I am zero!', b'I am one!']],
      dtype=object)>

### Otras operaciones matematicas

- Squaring, 
- log, 
- square root

In [69]:
# crear un nuevo tensor
H = tf.range(0,10)
H

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [70]:
# Elevar al cuadrado los valores de un tensor
tf.square(H)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [71]:
# Realizar la raíz cuadrada de un tensor
tf.sqrt(tf.cast(H, dtype=tf.float16))

<tf.Tensor: shape=(10,), dtype=float16, numpy=
array([0.   , 1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828,
       3.   ], dtype=float16)>

In [72]:
# Calcular el logaritmo de un tensor
tf.math.log(tf.cast(H, dtype=tf.float16))

<tf.Tensor: shape=(10,), dtype=float16, numpy=
array([  -inf, 0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 ,
       2.08  , 2.197 ], dtype=float16)>

In [73]:
# Calcular la exponencial de un tensor
tf.exp(tf.cast(H, dtype=tf.float16))

<tf.Tensor: shape=(10,), dtype=float16, numpy=
array([1.000e+00, 2.719e+00, 7.391e+00, 2.008e+01, 5.459e+01, 1.484e+02,
       4.035e+02, 1.097e+03, 2.980e+03, 8.104e+03], dtype=float16)>

### Tensors y Numpy

TensorFlow interactúa perfectamente con NumPy.

:warning: **Nota**: Cuando se trabaja con tensores y NumPy, los tensores toman la prioridad. Es decir, si se tiene un tensor y un array de NumPy, y se realiza una operación con ambos, el resultado será un tensor.

:warning: **Nota**: La diferencia de crear un tensor con TensorFlow y con NumPy es que cuando se crea un tensor con TensorFlow, se crea en la memoria de la GPU, mientras que cuando se crea un tensor con NumPy, se crea en la memoria de la CPU.


In [74]:
# Crear un tensor directamente desde un numpy array

J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [75]:
# Convertir un tensor a un numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [76]:
# Convertir un tensor a un numpy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [77]:
# El valor por defencto de cada uno es un poco diferente

numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

# Comprobar el tipo de dato de cada tensor
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPU

Como se ha mencionado anteriormente, TensorFlow puede trabajar con la GPU. Para comprobar si TensorFlow está utilizando la GPU, podemos utilizar `tf.config.list_physical_devices()`.

In [80]:
# Comprobar si la GPU está disponible

tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [81]:
!nvidia-smi

Thu Dec  1 22:04:37 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 526.47       Driver Version: 526.47       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   50C    P8     4W /  N/A |   4151MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

> :key: **Nota**: Si se tiene acceso a una GPU, TensorFlow la utilizará por defecto. Si no se tiene acceso a una GPU, TensorFlow utilizará la CPU.

## :hammer: :wrench: Ejercicios

1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape [5, 300].
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
7. Find the min and max values of the tensor you created in 6.
8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.

In [82]:
# 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
Ejercicio_1 = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
Ejercicio_1

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])>

In [83]:
# 2. Encuentre la forma, dimensión y tamaño de los tensores que creó en 1.
Ejercicio_1.shape, Ejercicio_1.ndim, tf.size(Ejercicio_1).numpy()

(TensorShape([10]), 1, 10)

In [84]:
# 3. Crear dos tensores que contengan valores aleatorios entre 0 y 1 con forma [5,300].
Ejercicio_3_1 = tf.random.uniform(shape=[5, 300])
Ejercicio_3_2 = tf.random.uniform(shape=[5, 300])

In [85]:
#4. Multiplica los dos tensores que creaste en 3 usando la multiplicación matricial.
tf.matmul(Ejercicio_3_1, tf.transpose(Ejercicio_3_2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[72.63515 , 73.275154, 72.478745, 73.89535 , 77.06909 ],
       [76.14803 , 77.38722 , 76.156006, 78.477905, 77.93587 ],
       [74.061386, 75.79872 , 74.00404 , 74.95445 , 74.85766 ],
       [72.6186  , 77.07386 , 72.674484, 75.916084, 73.15647 ],
       [74.65546 , 76.221756, 75.43701 , 76.920525, 76.65762 ]],
      dtype=float32)>

In [88]:
# 5. multiplicar los dos tensores creados utilizando el producto punto. 

tf.tensordot(Ejercicio_3_1, tf.transpose(Ejercicio_3_2), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[72.63515 , 73.275154, 72.478745, 73.89535 , 77.06909 ],
       [76.14803 , 77.38722 , 76.156006, 78.477905, 77.93587 ],
       [74.061386, 75.79872 , 74.00404 , 74.95445 , 74.85766 ],
       [72.6186  , 77.07386 , 72.674484, 75.916084, 73.15647 ],
       [74.65546 , 76.221756, 75.43701 , 76.920525, 76.65762 ]],
      dtype=float32)>

In [86]:
# 6. Cree un tensor con valores aleatorios entre 0 y 1 con forma [224, 224, 3].

Ejercicio_5 = tf.random.uniform(shape=[224, 224, 3])

In [87]:
# 7. Encuentre el mínimo y máximo de los valores en el tensor que creó en 5.
tf.reduce_min(Ejercicio_5), tf.reduce_max(Ejercicio_5)

(<tf.Tensor: shape=(), dtype=float32, numpy=1.4781952e-05>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9999968>)

In [90]:
# 8. Crear un tensor con valores aleatorios de shape [1, 224, 224, 3], despues squeeze it para cambiar el shape a [224, 224, 3]
Ejercicio_8 =  tf.random.uniform(shape=[1,224, 224, 3])
Ejercicio_8_squeezed = tf.squeeze(Ejercicio_8)
Ejercicio_8_squeezed.shape, Ejercicio_8_squeezed.ndim

(TensorShape([224, 224, 3]), 3)

In [96]:
# 9. Crear un tensor con shape [10] usando utilizando valores aleatorios, despues encontrar el indice que tiene el valor maximo. 
Ejercicio_9 = tf.random.uniform(shape = [10],maxval=10, dtype=tf.int32)
Ejercicio_9, tf.argmax(Ejercicio_9)

(<tf.Tensor: shape=(10,), dtype=int32, numpy=array([9, 9, 4, 0, 4, 3, 1, 6, 2, 9])>,
 <tf.Tensor: shape=(), dtype=int64, numpy=0>)

In [97]:
# 10 aplicar one-hot encoder al tensor creado en el punto 9

# one hot encode some_list
depth = tf.size(Ejercicio_9).numpy()
tf.one_hot(Ejercicio_9, depth=depth)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>